# Main Workflow for Building & Publishing Github Containers to ghcr.io
name: Docker Build & Publish to GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract BITNAMI_TAG from Dockerfile
        id: bitnami_tag
        run: |
          TAG=$(grep -Po 'ARG BITNAMI_TAG=\K[^ ]+' Dockerfile)
          echo "bitnami_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.bitnami_tag.outputs.bitnami_tag }}
